### ISSUE TITLE
How to fork Neo to my new Blockchain Chain?

### ISSUE THREAD

**Issue by prateektiwari7** [CityOfZion/awesome-neo#115]
Hello CityOfZion Team 

How can I fork neo blockchain and change some basic configurations like Neo name, supply etc.

What are the build instructions for this?

**Comment by prateektiwari7** [comment]
thanks @corollari 

For replying back to this issue. Yes, I clone this repo, but what I can see there are no such instructions for Mac, Linux to build. I don't have a windows system. 

Can you please provide me any instructions to modify the code and build it.


Thanks, brother

**Comment by corollari** [comment]
See https://docs.neo.org/docs/en-us/node/cli/publish.html for how to build the code from source in non-windows systems. Regarding the modification of the code to change some parameters you can change some of them via the protocol.json file. If you want to do further modifications I can't help you.

**Comment by prateektiwari7** [comment]
Thanks @corollari
