### ISSUE TITLE
Addition of APIs to interact with the blockchain

### ISSUE THREAD

**Issue by metachris** [CityOfZion/awesome-neo#38]
Starting with an issue instead of PR to first collect infos, input and references.

API List:

* [NEO API documentation](http://docs.neo.org/en-us/node/api.html) (possibly outdated)
* [Neon wallet official REST API](https://github.com/CityOfZion/neon-wallet-db#overview-of-api)
 * @ixje: "Please add in that description that the overview is partially outdated. It mixes /v1/ and /v2 api calls in the description and examples, while they all have a working /v2/ version."
* https://neoscan.io/doc/Neoscan.Api.html

**Comment by ixje** [comment]
for the first bullet: I don't know where the "possibly outdated" comes from, but I recently PR'ed updating the RPC api list https://github.com/neo-project/docs/pull/224 so it is probably up to date now, unless the Chinese version was still outdated as well.

**Comment by anfn101** [comment]
Any update @metachris @ixje ?

**Comment by ixje** [comment]
I'd say remove `neon-wallet-db` as it's being depreciated and refer to them `neoscan` instead. Other than that I'm not aware of other public API's or resources that are not already in the above list. Unless we want to add C#/Python/<insert language> RPC clients/servers?

**Comment by metachris** [comment]
No progress at the moment. Closing this for now.
