### ISSUE TITLE
Create subsections under Developer Documentation  for C# Developers

### ISSUE THREAD

**Issue by mwherman2000** [CityOfZion/awesome-neo#64]
Per the discussion that started at the bottom of this PR: https://github.com/CityOfZion/awesome-neo/pull/63

RE: Should we perhaps start to add subsections to the Developer Documentation?

I think that's a good idea ...thought it for this PR but I'm glad you brought it up. I'm accumulating a fair bit of C# content that could easily command it's own subsection.

Going back to your comment about "yours is quite specific", "What is the subset of C# supported by the NEO compiler and NEO VM" is in fact the #1 topic for C#.NEO developers. It should be more accessible.

**Comment by mwherman2000** [comment]
I propose we use the Discord channel names (e.g. dev-general, csharp, python, ....) as our subcategories.

If there's no objections, I will go ahead with this, this week.   #crossposting to @coz_general

**Comment by metachris** [comment]
I think those would be good first subsections to start with:

* General
* C#
* Python
* JS

**Comment by revett** [comment]
@mwherman2000 Good idea but I agree with @metachris that we should proper names.

Discord channels are named like that due to the limitations of Discord, no need to bring those into a README 👍

**Comment by mwherman2000** [comment]
I've going to close this because it originally was a work item for me to restructure the C# developer resources ...within the larger context of the other languages supported on NEO (as we've all been discussing).

Thinking about this some more, C#.NEO developers need more a new subcategory and few links.  So I've initiated the "NEO Blockchain C# Developer Center of Excellence" (https://github.com/mwherman2000/neo-csharpcoe/blob/master/README.md).  

This might be a pattern for the other languages to consider/follow.
