### ISSUE TITLE
Nice to Have: Competitions/Hacktalon

### ISSUE THREAD

**Issue by jonatanblockchain** [CityOfZion/awesome-neo#66]
Could be nice have add a new section called Competitions/Hacktalon with all the projects presented, with the github links. I will auto-assign this.

**Comment by metachris** [comment]
Sure, would be great to list projects. Perhaps in a separate file outside the readme, else it's getting too big. Please add them with a PR. 👍

**Comment by jonatanblockchain** [comment]
@metachris also, what do you think remove Exchange section or move in a separate file? I think is a good idea only put dev resources on awesome-neo

**Comment by metachris** [comment]
Yes, I agree - the exchanges section is quite big and it would be great to put that into a separate file. Would you create a PR for this?
